sylius_grid:
    grids:
        vanssa_sylius_slider_admin_slide:
            driver:
                name: doctrine/orm
                options:
                    class: Vanssa\SyliusSliderPlugin\Entity\Slide
            sorting:
                position: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                position:
                    type: string
                    label: sylius.ui.position
                    sortable: ~
                slider:
                    type: twig
                    label: vanssa_sylius_slider.ui.sliders
                    path: .
                    options:
                        template: '@VanssaSyliusSliderPlugin/admin/grid/field/slide_slider.html.twig'
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: '@SyliusAdmin/shared/grid/field/boolean.html.twig'
                        vars:
                            th_class: 'w-1 text-center'
            filters:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: string
                    label: sylius.ui.name
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
